### ISSUE TITLE
HTML background not reflecting in front end

### ISSUE THREAD

**Issue by mohammedaz33m** [mohammedaz33m/Car_Price_Prediction#1]
There is a image img1 in templates folder. When we open it in chrome the background is shown but, when app.py is run the background is white. 

The desiresd UI is shown in repo readme section. There seems to be some issue with the jinja2 syntax. Need a fix for this.

**Comment by AnshulHedau** [comment]
Created the Pull Request to address this issue : https://github.com/mohammedaz33m/Car_Price_Prediction/pull/2

**Comment by AnshulHedau** [comment]
https://github.com/mohammedaz33m/Car_Price_Prediction/pull/2

**Comment by AnshulHedau** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21137234/97413383-bb7f4b00-1928-11eb-9d24-63b17ced521a.png">

**Comment by mohammedaz33m** [comment]
Hi, Anshul,
Give me some time to review it. I'll update you asap
